//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Scheduler.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ScheduleConfigDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ScheduleConfigDBEntities object using the connection string found in the 'ScheduleConfigDBEntities' section of the application configuration file.
        /// </summary>
        public ScheduleConfigDBEntities() : base("name=ScheduleConfigDBEntities", "ScheduleConfigDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ScheduleConfigDBEntities object.
        /// </summary>
        public ScheduleConfigDBEntities(string connectionString) : base(connectionString, "ScheduleConfigDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ScheduleConfigDBEntities object.
        /// </summary>
        public ScheduleConfigDBEntities(EntityConnection connection) : base(connection, "ScheduleConfigDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ScheduleConfiguration> ScheduleConfigurations
        {
            get
            {
                if ((_ScheduleConfigurations == null))
                {
                    _ScheduleConfigurations = base.CreateObjectSet<ScheduleConfiguration>("ScheduleConfigurations");
                }
                return _ScheduleConfigurations;
            }
        }
        private ObjectSet<ScheduleConfiguration> _ScheduleConfigurations;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ScheduleConfigurations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToScheduleConfigurations(ScheduleConfiguration scheduleConfiguration)
        {
            base.AddObject("ScheduleConfigurations", scheduleConfiguration);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ScheduleConfigDBModel", Name="ScheduleConfiguration")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ScheduleConfiguration : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ScheduleConfiguration object.
        /// </summary>
        /// <param name="assemblyName">Initial value of the AssemblyName property.</param>
        /// <param name="typeName">Initial value of the TypeName property.</param>
        /// <param name="interval">Initial value of the Interval property.</param>
        /// <param name="dueTime">Initial value of the DueTime property.</param>
        /// <param name="paused">Initial value of the Paused property.</param>
        /// <param name="canPause">Initial value of the CanPause property.</param>
        /// <param name="id">Initial value of the Id property.</param>
        public static ScheduleConfiguration CreateScheduleConfiguration(global::System.String assemblyName, global::System.String typeName, global::System.Int64 interval, global::System.Int32 dueTime, global::System.Byte paused, global::System.Byte canPause, global::System.Int64 id)
        {
            ScheduleConfiguration scheduleConfiguration = new ScheduleConfiguration();
            scheduleConfiguration.AssemblyName = assemblyName;
            scheduleConfiguration.TypeName = typeName;
            scheduleConfiguration.Interval = interval;
            scheduleConfiguration.DueTime = dueTime;
            scheduleConfiguration.Paused = paused;
            scheduleConfiguration.CanPause = canPause;
            scheduleConfiguration.Id = id;
            return scheduleConfiguration;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AssemblyName
        {
            get
            {
                return _AssemblyName;
            }
            set
            {
                OnAssemblyNameChanging(value);
                ReportPropertyChanging("AssemblyName");
                _AssemblyName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AssemblyName");
                OnAssemblyNameChanged();
            }
        }
        private global::System.String _AssemblyName;
        partial void OnAssemblyNameChanging(global::System.String value);
        partial void OnAssemblyNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TypeName
        {
            get
            {
                return _TypeName;
            }
            set
            {
                OnTypeNameChanging(value);
                ReportPropertyChanging("TypeName");
                _TypeName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TypeName");
                OnTypeNameChanged();
            }
        }
        private global::System.String _TypeName;
        partial void OnTypeNameChanging(global::System.String value);
        partial void OnTypeNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Interval
        {
            get
            {
                return _Interval;
            }
            set
            {
                OnIntervalChanging(value);
                ReportPropertyChanging("Interval");
                _Interval = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Interval");
                OnIntervalChanged();
            }
        }
        private global::System.Int64 _Interval;
        partial void OnIntervalChanging(global::System.Int64 value);
        partial void OnIntervalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DueTime
        {
            get
            {
                return _DueTime;
            }
            set
            {
                OnDueTimeChanging(value);
                ReportPropertyChanging("DueTime");
                _DueTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DueTime");
                OnDueTimeChanged();
            }
        }
        private global::System.Int32 _DueTime;
        partial void OnDueTimeChanging(global::System.Int32 value);
        partial void OnDueTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte Paused
        {
            get
            {
                return _Paused;
            }
            set
            {
                OnPausedChanging(value);
                ReportPropertyChanging("Paused");
                _Paused = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Paused");
                OnPausedChanged();
            }
        }
        private global::System.Byte _Paused;
        partial void OnPausedChanging(global::System.Byte value);
        partial void OnPausedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte CanPause
        {
            get
            {
                return _CanPause;
            }
            set
            {
                OnCanPauseChanging(value);
                ReportPropertyChanging("CanPause");
                _CanPause = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CanPause");
                OnCanPauseChanged();
            }
        }
        private global::System.Byte _CanPause;
        partial void OnCanPauseChanging(global::System.Byte value);
        partial void OnCanPauseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();

        #endregion

    
    }

    #endregion

    
}
